### ISSUE TITLE
Feature request: Allow to limit boost in custom training packs.

### ISSUE THREAD

**Issue by IDizor** [bakkesmodorg/BakkesModSDK#11]
For example when training fast kickoff (7EE0-F697-7453-7123) the boost is unlimited, and there is no option to limit boost in game settings. I need to limit boost like in real game to have proper training.

**Comment by daniel-dara** [comment]
Bakkes has this feature. Open Bakkes and go to the "Custom training" tab. The top slider bar is "Boost limit" and defaults to -1 (infinite). Adjust the slider to the right to limit boost however you want. Reset your current training shot and it will take effect.
