### ISSUE TITLE
Issue with input being dropped when using BakkesMod

### ISSUE THREAD

**Issue by ADustyOldMuffin** [bakkesmodorg/BakkesModSDK#16]
I play  using a mouse, and when I use BakkesMod it will drop mouse clicks where I will have to click many times before it goes through. I've tested it a lot to confirm (like 20 games with 20 games without) and this seems to be the cause.

**Comment by ADustyOldMuffin** [comment]
This still was never resolved?

**Comment by Stanbroek** [comment]
This was never a *BakkesModSDK* issue, that why it is closed.

**Comment by CinderBlocc** [comment]
If it's still an issue, please report it in the bakkesmod subreddit: https://old.reddit.com/r/bakkesmod/
