### ISSUE TITLE
"Hide all rank information" is broken

### ISSUE THREAD

**Issue by chasecaleb** [bakkesmodorg/BakkesModSDK#19]
Going to `Anonymizer -> Hide all rank information` does not work (i.e. rank is still shown on queue menu).

This has been broken since at least September 26, 2020 based on the thread creation date here: https://www.reddit.com/r/bakkesmod/comments/izzqwp/hide_all_rank_information/

Edit: Also sorry, I'm pretty sure this belongs in https://github.com/bakkesmodorg/BakkesMod2-Plugins instead of here.

**Comment by CinderBlocc** [comment]
Thanks for the report, and sorry for the delayed response. Since that plugin's source isn't public, the best place for reports about it is the subreddit where we are currently directing bug reports.
