### ISSUE TITLE
hi my epig games rocket league commit suisied when it opens and did try every single step on the (fandom website) so tell me how to open it and if u want any information just tell me

### ISSUE THREAD

**Issue by Ahmedelgamedfsj5** [bakkesmodorg/BakkesModSDK#23]

**Comment by CinderBlocc** [comment]
This is not the place to ask for general bakkesmod troubleshooting. This is the place to alert us to errors in the SDK if you are using it to develop a plugin. You have already made a post in the subreddit. Please do not spam this repo with any additional issues unrelated to the SDK itself.
