### ISSUE TITLE
Opacity issue with FillTriangle

### ISSUE THREAD

**Issue by Arubinu** [bakkesmodorg/BakkesModSDK#38]
Hello, I have been using BakkesMod for a short time, but I have a problem.

I am trying to draw a triangle with `CanvasWrapper` using the `FillTriangle` method.
But whether I set the color before or in the method, it doesn't take into account the opacity and therefore remains completely opaque.

Do you have a solution to my problem?

PS: Could you add a method for Polygons and Circles? :D

**Comment by Bakkes** [comment]
All the canvas wrapper do is wrap around the original UE3 Canvas class (https://docs.unrealengine.com/udk/Three/CanvasTechnicalGuide.html), and the code passes the color on correctly. Now, the wrapper calls a function DrawTris but I can't find any documentation of that anywhere online, so I guess that's implemented by Psyonix themselves maybe, or just not very well known. 

This issue has come up before in the programming discord (listed in the readme).  But my/our best guess is that the opacity value that's passed in the color struct is simply ignored and a hardcoded value is used, so there's not much we can do about that. As for the polygons and circles, check out the RenderingTools library which contains support for circles (https://github.com/CinderBlocc/RenderingTools). I guess polygons are possible but you'd have to triangulate it yourself.

**Comment by Arubinu** [comment]
Ah ok I understand.
Thank you for all these explanations :)
