### ISSUE TITLE
CanvasWrapper has no methods for 3D drawing.

### ISSUE THREAD

**Issue by videogame-hacker** [bakkesmodorg/BakkesModSDK#4]
I am writing a plugin to help aiming at specific points in the goal (to evade defenders and such) and would like to draw in 3D space.

The current CanvasWrapper provides no way to draw in 3D space.

Perhaps if something like gluProject from OpenGL utils were added, 3D->2D could be achieved easily.

**Comment by Bakkes** [comment]
Well to be honest I don't know a lot about converting from 3D into 2D space. What types of info would be needed to create a method that does this? Currently the camera location + other info is exposed. Is that enough to create such a method? I'm not quite sure where I'd be able to get the projectionmatrix and such from.

**Comment by CinderBlocc** [comment]
CanvasWrapper::Project and ProjectF can achieve this now by projecting a 3D vector to 2D screenspace coordinates.
