### ISSUE TITLE
ModalWrapper fails to set Icon

### ISSUE THREAD

**Issue by Gtt1229** [bakkesmodorg/BakkesModSDK#60]
Specifying an icon fails to change the modal in game:

ex:
```
ModalWrapper updateModal = gameWrapper->CreateModal("Plugin Change");
updateModal.SetIcon("gfx_shared.Icon_Warning");
```

**Comment by Bakkes** [comment]
Looks like it expects the icon name to be `Texture2D gfx_shared.Icon_Warning`. I'll make it so the next version of BM doesn't require the `Texture2D ` prefix, but for now you'll have to use it. (Next version of BM should accept both with and without)

Thanks for the report!
