### ISSUE TITLE
If "show casual MMR in queue menu" is enabled = buggy

### ISSUE THREAD

**Issue by pickonedev** [bakkesmodorg/BakkesModSDK#73]
Hi!

This is happening
Enabled
![image](https://github.com/bakkesmodorg/BakkesModSDK/assets/34201387/59af575f-0cd8-4fb0-861f-a9319f325d0a)

Disabled
![image](https://github.com/bakkesmodorg/BakkesModSDK/assets/34201387/dd0c806c-15e1-4bc9-b9ad-492e698d8675)

**Comment by Bakkes** [comment]
Thanks for the report! I've pushed an update that should resolve this issue.
