### ISSUE TITLE
Feature Request: Mac support

### ISSUE THREAD

**Issue by nathan-fiscaletti** [bakkesmodorg/BakkesModSDK#8]
I would love to be able to use Bakkesmod on my Mac as I don't play on a windows machine.

**Comment by ignasbernotas** [comment]
I'd love to contribute to the OSX version, however I really don't know where to start.. any tips are welcome :)

**Comment by AppleRocks307** [comment]
> I'd love to contribute to the OSX version, however I really don't know where to start.. any tips are welcome :)

What do you need? I might be able to help, although I have absolutely no technical skill

**Comment by Lazyboy007** [comment]
Second this. I could probably help with porting it, and I use mac myself.

**Comment by JohannesHoffmann** [comment]
Not necessary anymore... Rocketleage stops support for linux and mac
https://support.rocketleague.com/hc/en-us/articles/360042201433

ticket could be closed i guess... unfortunately :(

**Comment by Lazyboy007** [comment]
indeed :/

**Comment by nathan-fiscaletti** [comment]
> Not necessary anymore... Rocketleage stops support for linux and mac
> https://support.rocketleague.com/hc/en-us/articles/360042201433
> 
> issue could be closed i guess... unfortunately :(

😭 thankfully i have a ps4.

_proceedes to open an issue about some how supporting PS4_
